# Generated by Django 5.0.2 on 2024-04-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listmembers", "0004_rename_telefone_negocios_contato_telefonico_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="negocios",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("limpeza", "Limpeza"),
                    ("manutencao", "Manutenção"),
                    ("restaurante", "Restaurante"),
                    ("informatica", "Informática"),
                    ("beleza", "Beleza"),
                    ("moda", "Moda"),
                    ("alimentacao", "Alimentação"),
                    ("indefinido", "Indefinido"),
                    ("papelaria", "Papelaria"),
                ],
                default="Prestador de Serviço",
                max_length=20,
            ),
        ),
    ]
