# Generated by Django 5.0.2 on 2024-04-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Morador",
        ),
        migrations.DeleteModel(
            name="PrestadorDeServico",
        ),
    ]
