# Generated by Django 5.0.2 on 2024-05-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0007_alter_negocio_categoria_alter_negocio_tipo_negocio"),
    ]

    operations = [
        migrations.AddField(
            model_name="negocio",
            name="whatsappContato",
            field=models.URLField(blank=True, null=True),
        ),
    ]
