# Generated by Django 5.0.2 on 2024-05-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0008_negocio_whatsappcontato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="negocio",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="negocio",
            name="whatsappContato",
            field=models.CharField(blank=True, null=True),
        ),
    ]
