# Generated by Django 5.0.2 on 2024-05-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0009_alter_negocio_email_alter_negocio_whatsappcontato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="negocio",
            name="endereco",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
