# Generated by Django 5.0.2 on 2024-05-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0011_alter_negocio_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="negocio",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("limpeza", "Limpeza"),
                    ("manutencao", "Manutenção"),
                    ("restaurante", "Restaurante"),
                    ("informatica", "Informática"),
                    ("beleza", "Beleza"),
                    ("moda", "Moda"),
                    ("alimentacao", "Alimentação"),
                    ("indefinido", "Indefinido"),
                    ("papelaria", "Papelaria"),
                    ("moveisPlanejados", "Moveis Planejados"),
                    ("imobiliaria", "Imobiliária"),
                    ("marcenaria", "Marcenaria"),
                    ("eventos", "Eventos"),
                    ("decoracao", "Decoração"),
                    ("grafica", "Gráfica"),
                    ("farmacia", "Farmácia"),
                    ("montagem", "Montagem"),
                    ("paraSeuPet", "Para seu pet"),
                    ("entretenimento", "Entretenimento"),
                    ("seguros", "Seguros"),
                ],
                default="Indefinido",
                max_length=20,
            ),
        ),
    ]
