# Generated by Django 5.0.2 on 2024-05-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0013_alter_negocio_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="negocio",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="negocio",
            name="endereco",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="negocio",
            name="endereco_site",
            field=models.URLField(blank=True, default=""),
        ),
    ]
