# Generated by Django 5.0.2 on 2024-05-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0014_alter_negocio_email_alter_negocio_endereco_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="negocio",
            name="contato_telefonico",
            field=models.CharField(max_length=50),
        ),
    ]
